apiVersion: apps/v1
kind: Deployment
metadata:
  name: greencart-frontend
  namespace: greencart
  labels:
    app: greencart-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greencart-frontend
  template:
    metadata:
      labels:
        app: greencart-frontend
    spec:
      containers:
        - name: frontend
          image: 547268988661.dkr.ecr.ap-south-1.amazonaws.com/greencart-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: greencart-frontend
  namespace: greencart
spec:
  selector:
    app: greencart-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer